import type {
  ConfigExtension,
  DefaultClassGroupIds,
  DefaultThemeGroupIds,
} from 'tailwind-merge'

type TwMergeExtend = NonNullable<
  ConfigExtension<DefaultClassGroupIds, DefaultThemeGroupIds>['extend']
>

export const twMergeExtend: TwMergeExtend = {
  theme: {
    breakpoint: ['desktop-m', 'desktop-s', 'tablet-s', 'mobile-m', 'mobile-s'],
  },
  classGroups: {
    'font-size': [
      {
        text: [
          'caption',
          'display',
          'hint',
          'lead',
          'regular',
          'title-1',
          'title-2',
          'title-3',
          'title-4',
        ],
      },
    ],
    leading: [
      {
        leading: [
          'caption',
          'display',
          'hint',
          'lead',
          'regular',
          'title-1',
          'title-2',
          'title-3',
          'title-4',
        ],
      },
    ],
    p: [
      {
        p: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    px: [
      {
        px: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    py: [
      {
        py: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    pt: [
      {
        pt: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    pr: [
      {
        pr: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    pb: [
      {
        pb: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    pl: [
      {
        pl: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    ps: [
      {
        ps: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    pe: [
      {
        pe: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    m: [
      {
        m: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    mx: [
      {
        mx: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    my: [
      {
        my: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    mt: [
      {
        mt: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    mr: [
      {
        mr: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    mb: [
      {
        mb: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    ml: [
      {
        ml: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    ms: [
      {
        ms: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    me: [
      {
        me: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    gap: [
      {
        gap: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'gap-x': [
      {
        'gap-x': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'gap-y': [
      {
        'gap-y': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'space-x': [
      {
        'space-x': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'space-y': [
      {
        'space-y': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    w: [
      {
        w: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
      {
        w: [
          '2xl',
          '2xs',
          '3xl',
          '3xs',
          '4xl',
          '5xl',
          '6xl',
          '7xl',
          'column-width',
          'lg',
          'md',
          'prose-measure',
          'sm',
          'xl',
          'xs',
        ],
      },
    ],
    'min-w': [
      {
        'min-w': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
      {
        'min-w': [
          '2xl',
          '2xs',
          '3xl',
          '3xs',
          '4xl',
          '5xl',
          '6xl',
          '7xl',
          'column-width',
          'lg',
          'md',
          'prose-measure',
          'sm',
          'xl',
          'xs',
        ],
      },
    ],
    h: [
      {
        h: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'min-h': [
      {
        'min-h': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    size: [
      {
        size: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    inset: [
      {
        inset: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'inset-x': [
      {
        'inset-x': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'inset-y': [
      {
        'inset-y': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    top: [
      {
        top: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    right: [
      {
        right: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    bottom: [
      {
        bottom: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    left: [
      {
        left: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    start: [
      {
        start: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    end: [
      {
        end: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'translate-x': [
      {
        'translate-x': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'translate-y': [
      {
        'translate-y': [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    basis: [
      {
        basis: [
          'content-outer',
          'content-outer-padded',
          'content-padding',
          'content-width',
          'experience-column-width',
          'footer-height',
          'grid-gap-regular',
          'intersection-padding',
          'magazine-padding',
          'section-padding',
        ],
      },
    ],
    'max-w': [
      {
        'max-w': [
          '2xl',
          '2xs',
          '3xl',
          '3xs',
          '4xl',
          '5xl',
          '6xl',
          '7xl',
          'column-width',
          'lg',
          'md',
          'prose-measure',
          'sm',
          'xl',
          'xs',
        ],
      },
    ],
  },
}

export const themeColors = {
  accent: '#ff6a1f',
  'atomic-orange': '#fff70a',
  background: 'var(--color-base)',
  base: '#000',
  black: '#000',
  edge: 'rgb(83, 76, 76)',
  info: '#4d8dff',
  muted: '#8b8484',
  surface: '#131418',
  system: '#34e39b',
  text: '#fff',
  white: '#fff',
} as const
